jobs:
  setup-and-launch:
    ssh:
      remoteHost: ${{ inputs.resources.whost.ip }}
    steps:
      - name: Display run context
        run: |
          echo "Print hostname..."
          hostname
          echo "Print date..."
          date
          echo "Print pwd..."
          pwd
          echo "Print local user: ${USER}"
      - name: Install GitHub CLI
        # This step is only required if we need to
        # push to the repository later. By checking
        # for whether we need to push here, we can
        # run the workflow manually with an empty 
        # GITHUB_TOKEN for debugging, etc.
        if: ${{ inputs.repositories.push_to_gh }}
        run: |
          mkdir -p ~/bin
          rm -rf ~/bin/gh*
          wget https://github.com/cli/cli/releases/download/v2.93.0/gh_2.93.0_linux_amd64.tar.gz -O gh.tar.gz
          tar -xzf gh.tar.gz -C ~/bin
          rm gh.tar.gz
          cd ~/bin
          mv gh* gh
      - name: Setup GitHub CLI and git
        # This step is only required if pushing to GitHub
        if: ${{ inputs.repositories.push_to_gh }}
        env:
          GITHUB_TOKEN: ${{ inputs.repositories.ml_arch_token }}
          GH_TOKEN: ${{ inputs.repositories.ml_arch_token }}
        run: |
          export "PATH=${PATH}:~/bin/gh/bin"
          echo "Length check:"
          echo "len=${#GH_TOKEN}"
          echo "Start check:"
          echo "first=${GH_TOKEN:0:4}"
          echo $GITHUB_TOKEN | gh auth login --with-token
          #gh auth status
          if [[ ${GH_TOKEN:0:4} == "ghs_" ]]; then
            # Using GITHUB_TOKEN from Action
            gh_login_name="github-actions[bot]"
          else
            # Using a PAT
            gh_login_name=$(gh api user -q ".login" 2>/dev/null)
          fi
          # Autodectect one liner does not always work.
          #gh_login_name=$(gh api user -q ".login" 2>/dev/null || echo "github-actions[bot]")
          echo Detected GitHub login name: ${gh_login_name}
          git config --global user.name ${gh_login_name}
          git config --global user.email ${gh_login_name}@users.noreply.github.com
          gh auth setup-git
      - name: Clone repositories
        # Force all repos to pull.  The clone operations
        # may fail if the repo already exists (i.e. a cluster
        # is being used again to run the workflow again). However,
        # in that case, it is essential that the repos pull in
        # any new updates (because the clone failed, so nothing
        # new was pulled).
        run: |
          echo Changing to top level working directory
          cd ${{ inputs.resources.top_work_dir }}
          pwd
          echo Cloning archive repository...
          git clone ${{ inputs.repositories.ml_arch_repo }}
          echo Adding/Checking out archive branch...
          cd $(basename ${{ inputs.repositories.ml_arch_repo }} )
          git branch ${{ inputs.repositories.ml_arch_branch }}
          git checkout ${{ inputs.repositories.ml_arch_branch }}
          # If the branch does not already exist, the following
          # will result in an error but the workflow continues.
          # The check is included here since under most 
          # circumstances it is expected that the branch will already
          # exist when pushing to GitHub and the branch will NOT
          # already exist when not pushing to GitHub (a manual test run).
          if [[ "${{ inputs.repositories.push_to_gh }}" == "true" ]]; then
            echo Set upstream branch in case it exists already...
            git branch --set-upstream-to=origin/${{ inputs.repositories.ml_arch_branch }} ${{ inputs.repositories.ml_arch_branch }}
          fi
          git pull
          cd ${{ inputs.resources.top_work_dir }}
          echo Cloning ML code repository...
          git clone ${{ inputs.repositories.ml_code_repo }}
          cd $(basename ${{ inputs.repositories.ml_code_repo }} )
          git pull
          cd ${{ inputs.resources.top_work_dir }}
          echo Cloning ML data repository...
          git clone ${{ inputs.repositories.ml_data_repo }}
          cd $(basename ${{ inputs.repositories.ml_data_repo }} )
          git pull
          cd ${{ inputs.resources.top_work_dir }}
      - name: Install Miniconda and setup Python stack
        run: |
          echo "======> Test for presence of Conda environment"
          ls ${{ inputs.resources.miniconda_loc }}
          if [ $? -ne 0 ]; then
            echo "======> No Conda found; install Conda environment for SuperLearner."
            echo This process can take several minutes.
            cd ${{ inputs.resources.top_work_dir }}
            cd $(basename ${{ inputs.repositories.ml_code_repo }} )
            ./create_conda_env.sh ${{ inputs.resources.miniconda_loc }} ${{ inputs.resources.my_env }}
          else
            echo "======> Conda found!  Assuming no need to install."
          fi
      - name: Run preprocessing
        #===============================================
        # TO DO: Standardize how features and targets are
        # specified for the workflow. This is slightly
        # complicated by the fact that the workflow
        # builds the training data on-the-fly by merging
        # multiple data sets. Once we do this, we won't
        # need to hard code the target name as done 
        # immediately below.
        #===============================================
        # Temporary storage for the original predict var
        # from various other iterations:
        # Respiration_Rate_mg_DO_per_L_per_H
        # Temporary storage for the best predict var
        # Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment
        run: |
          echo "===================================="
          echo "Setting target name..."
          target_name="Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment"
          echo "Set target name to ${target_name}"
          echo "===================================="
          cd ${{ inputs.resources.top_work_dir }}
          cd $(basename ${{ inputs.repositories.ml_arch_repo }} )
          cd scripts
          ./preprocess.sh ${{ inputs.resources.miniconda_loc }} ${{ inputs.resources.my_env }} ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_data_repo }} ) ${target_name}
      - name: Run learning and model evaluation
        # Here we launch 10 independent, simultaneous 
        # ML jobs based on num_inst, below. The first
        # stage of the loop will remove any existing
        # files in work_dir_base in case the workflow
        # is rerunning on a cluster that experienced
        # a crash.
        run: |
          echo "===================================="
          echo "Setting target name..."
          target_name="Normalized_Respiration_Rate_mg_DO_per_H_per_L_sediment"
          echo "Set target name to ${target_name}"
          echo "===================================="
          for (( ii=0; ii<${{ inputs.superlearner.num_inst }}; ii++ ))
          do
            # Launch a single SuperLearner job
            work_dir=${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_arch_repo }} )/${work_dir_base}${ii}
            echo "=======> Deleting any existing data in ${work_dir}"
            rm -rf ${work_dir}
            echo "=======> Creating work dir: ${work_dir}"
            mkdir -p ${work_dir}
            echo "======> Building job card ${ii}"
            cat << EOF > sl.${{ inputs.repositories.ml_arch_branch }}.${ii}.sbatch
            #!/bin/bash
            #SBATCH --exclusive
            #SBATCH --job-name=${{ inputs.repositories.ml_arch_branch }}.${ii}
            #SBATCH --output=sl.std.out.${{ inputs.repositories.ml_arch_branch }}.${ii}
            cd ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_code_repo }})
            ./train_predict_eval.sh \
            ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_arch_repo }})/${{ inputs.superlearner.train_test_data }} \
            ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_arch_repo }})/${{ inputs.superlearner.train_test_groups }} \
            ${{ inputs.superlearner.num_inputs }} \
            ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_code_repo }})/${{ inputs.superlearner.superlearner_conf }} \
            ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_arch_repo }})/${{ inputs.superlearner.work_dir_base }} \
            ${{ inputs.resources.miniconda_loc }} \
            ${{ inputs.resources.my_env }} \
            ${{ inputs.superlearner.hpo }} \
            ${{ inputs.superlearner.cross_val_score }} \
            ${{ inputs.superlearner.smogn }} \
            ${{ inputs.superlearner.onnx }} \
            ${{ inputs.superlearner.n_jobs }} \
            ${{ inputs.superlearner.backend }} \
            ${target_name} \
            ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_arch_repo }})/${{ inputs.superlearner.predict_data }} \
            ${{ inputs.superlearner.fpi_corr_cutoff }}
          EOF
            echo "======> Launching SuperLearner ${ii}"
            sbatch sl.${{ inputs.repositories.ml_arch_branch }}.${ii}.sbatch
          done
          echo "===================================="
      - name: Monitor jobs on cluster
        # Check if there are any other running jobs on the cluster
        # by counting the number of lines in squeue output. One
        # line is the header line => no jobs are running.  Anything
        # more than 1 means that there is at least one job running.
        run: |
          n_squeue="2"
          squeue_wait=10
          while [ $n_squeue -gt 1 ]
          do
            # Wait first - sbatch launches may take
            # a few seconds to register on squeue!
            echo "Monitor waiting "${squeue_wait}" seconds..."
            sleep $squeue_wait
            n_squeue=$(squeue | wc -l )
            echo "Found "${n_squeue}" lines in squeue."
          done
          echo "No more pending jobs in squeue.
      - name: Run postprocessing
        # TODO: Address platform side logs. Old log staging
        # is commented out below.
        run: |
          cd ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_arch_repo }})/scripts
          ./postprocess.sh ${{ inputs.resources.miniconda_loc }} ${{ inputs.resources.my_env }} ${{ inputs.resources.top_work_dir }}/$(basename ${{ inputs.repositories.ml_data_repo }})
          #echo "======> Stage PW logs to remote repo for committing"
          #rsync -av ./logs.out $remote_user@$remote_node:${abs_path_to_arch_repo}/output_data/logs.out
      - name: Push branch to archive repository
        if: ${{ inputs.repositories.push_to_gh }}
        env:
          GITHUB_TOKEN: ${{ inputs.repositories.ml_arch_token }}
        run: |
          export "PATH=${PATH}:~/bin/gh/bin"
          echo $GITHUB_TOKEN | gh auth login --with-token
          cd ${{ inputs.resources.top_work_dir }}
          cd $(basename ${{ inputs.repositories.ml_arch_repo }} )
          #cd output_data
          #date > test.txt
          git add --all .
          git commit -m "ICON-ModEx iteration on $(date)"
          git push origin ${{ inputs.repositories.ml_arch_branch }}
'on':
  execute:
    inputs:
      repositories:
        label: Repositories and branches
        type: group
        collapsed: false
        items:
          ml_arch_repo:
            label: ML archive repository
            type: string
            default: https://github.com/parallelworks/dynamic-learning-rivers
            tooltip: Repo MUST have SSH prefix, e.g. git@github.com:org/repo, for SSH auth w/ deploy keys to push
          ml_arch_branch:
            label: ML archive branch
            type: string
            default: test-auto-workflow
          ml_arch_token:
            label: GitHub Token
            type: password
            default: ghp_...
            tooltip: When launching this workflow manually from the form, you can use your GitHub Personal Access Token. When running this workflow via a GitHub Action, you can use the repository ${{ secrets.GITHUB_TOKEN }}
          push_to_gh:
            label: Push results to GitHub
            type: boolean
            tooltip: Select yes to push results to GitHub. A deploy key for the repo is required.
          ml_code_repo:
            label: ML code repository
            type: string
            default: https://github.com/parallelworks/sl_core
          ml_data_repo:
            label: ML data repository
            type: string
            default: https://github.com/parallelworks/global-river-databases
      resources:
        label: Resources and compute environments
        type: group
        collapsed: false
        items:
          whost:
            label: Workflow host (Slurm cluster name)
            type: compute-clusters
            autoselect: true
            optional: false
            tooltip: Name of cluster to run on. Select a resource from drop down menu.
          top_work_dir:
            label: Top level of working directory
            type: string
            tooltip: Top level of working directory. Must be on a shared directory (e.g. $HOME).
            default: ${HOME}
          miniconda_loc:
            label: Location (prefix) of Miniconda installation
            type: string
            default: ${HOME}/.miniconda3
            tooltip: Location of miniconda on cluster. ${USER} is auto substituted.'
          my_env:
            label: Name of Miniconda environment
            type: string
            default: superlearner
            tooltip: Specify name of Miniconda environment to use. There is a bug with using base!
      superlearner:
        label: SuperLearner configuration
        type: group
        collapsed: false
        items:
          train_test_data:
            label: Data for training and testing [.csv] [Inputs, Outputs]
            type: string
            tooltip: The header contains the parameter names; the inputs must occupy the first columns; path wrt ML archive repo.
            default: scripts/prep_06_output_final_train.csv
          train_test_groups:
            label: File [.csv] with column named gid listing group IDs
            type: string
            tooltip: Provide an integer group ID for each row in the training/test data for GroupShuffleSplit. Additional columns are ignored but can be used for referencing later.
            default: scripts/prep_06_output_final_train.ixy
          predict_data:
            label: Data for predicting [.csv] [Inputs, Outputs]
            type: string
            tooltip: The header contains the parameter names; only inputs; path wrt ML archive repo.
            default: scripts/prep_06_output_final_predict
          num_inputs:
            label: Number of inputs
            type: number
            default: 25
          superlearner_conf:
            label: SuperLearner configuration
            type: string
            tooltip: SuperLearner configuration; path wrt ML code repo
            default: sample_inputs/superlearner_conf.py
          work_dir_base:
            label: SuperLearner working directory basename wrt archive repo
            type: string
            default: ml_models/sl_
            tooltip: Prefix/base of the location where to store all SL output in the archive repo.
          hpo:
            type: boolean
            label: Run hyperparameter optimization?
            tooltip: Select yes for hyperparameter tuning
            default: true
          cross_val_score:
            type: boolean
            label: Run cross-validation?
            tooltip: Select yes to run cross-validation on the entire data set
            default: true
          smogn:
            type: boolean
            label: Use SMOGN to build synthetic data
            tooltip: Select yes to augment training data with synthetic data. UNDER DEVELOPMENT - CURRENTLY IGNORED.
            default: false
          onnx:
            type: boolean
            label: Save SuperLearner models in ONNX format
            tooltip: Select yes to save in ONNX format (more portable than .pkl). UNDER DEVELOPMENT - CURRENTLY IGNORED.
            default: false
          backend:
            type: dropdown
            label: Joblib backend
            tooltip: Select Backend
            options:
              - label: loky
                value: loky
              - label: multiprocessing
                value: multiprocessing
              - label: threading
                value: threading
              - label: dask
                value: dask
          n_jobs:
            label: Number of parallel jobs on worker
            type: number
            default: 8
          num_inst:
            label: Number of SuperLearner instances (duplicate stacked-regressors trained)
            type: number
            default: 10
          fpi_corr_cutoff:
            label: Correlation cutoff for FPI
            type: number
            default: 50
            tooltip: Features correlated above this level will be grouped in FPI analysis. This is correlation on scale of 0 to 100 (instead of 0 to 1), but not R^2!

